apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-01-23T20:54:26Z"
  name: carts-canary
  resourceVersion: "1023309"
  selfLink: /api/v1/namespaces/sockshop-production/services/carts
  uid: 8a7b9a32-3e22-11ea-95f1-42010a80001f
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: carts
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
