apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-01-23T20:47:26Z"
  name: carts-canary
  resourceVersion: "1021576"
  selfLink: /api/v1/namespaces/sockshop-staging/services/carts
  uid: 906dddf8-3e21-11ea-95f1-42010a80001f
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: carts
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
