apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: carts-db
spec:
  gateways:
  - sockshop-dev-gateway.sockshop-dev
  - mesh
  hosts:
  - carts-db.sockshop-dev.104.154.119.157.xip.io
  - carts-db
  - carts-db.sockshop-dev
  http:
  - route:
    - destination:
        host: carts-db.sockshop-dev.svc.cluster.local
